"""add_cloud_init_template_vmid_to_proxmox_servers

Revision ID: 2c9c6129ebb0
Revises: 7ed3d555f5b2
Create Date: 2026-01-28 04:03:48.989561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9c6129ebb0'
down_revision: Union[str, None] = '7ed3d555f5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxmox_servers', sa.Column('cloud_init_template_vmid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxmox_servers', 'cloud_init_template_vmid')
    # ### end Alembic commands ###
