"""add_proxmox_servers_table_and_vm_server_fk

Revision ID: 3cb6dfdd7cdb
Revises: 5bc36223ae32
Create Date: 2026-01-27 10:13:33.146348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb6dfdd7cdb'
down_revision: Union[str, None] = '5bc36223ae32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machines', sa.Column('proxmox_server_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_virtual_machines_proxmox_server_id'), 'virtual_machines', ['proxmox_server_id'], unique=False)
    op.create_foreign_key(None, 'virtual_machines', 'proxmox_servers', ['proxmox_server_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_machines', type_='foreignkey')
    op.drop_index(op.f('ix_virtual_machines_proxmox_server_id'), table_name='virtual_machines')
    op.drop_column('virtual_machines', 'proxmox_server_id')
    # ### end Alembic commands ###
