"""add_user_quota_fields

Revision ID: 5bc36223ae32
Revises: 
Create Date: 2026-01-27 07:27:06.475320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bc36223ae32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_disk_gb', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_ram_mb', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_vms', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('max_cpu_cores', sa.Integer(), nullable=True))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('virtual_machines', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('virtual_machines', 'os_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ubuntu-24.04'::character varying"))
    op.alter_column('virtual_machines', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'creating'::character varying"))
    op.alter_column('virtual_machines', 'proxmox_node',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('virtual_machines', 'storage',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('virtual_machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('virtual_machines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_vms_status', table_name='virtual_machines')
    op.drop_index('idx_vms_user_id', table_name='virtual_machines')
    op.drop_constraint('virtual_machines_vmid_key', 'virtual_machines', type_='unique')
    op.create_index(op.f('ix_virtual_machines_id'), 'virtual_machines', ['id'], unique=False)
    op.create_index(op.f('ix_virtual_machines_user_id'), 'virtual_machines', ['user_id'], unique=False)
    op.create_index(op.f('ix_virtual_machines_vmid'), 'virtual_machines', ['vmid'], unique=True)
    op.drop_constraint('virtual_machines_user_id_fkey', 'virtual_machines', type_='foreignkey')
    op.create_foreign_key(None, 'virtual_machines', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_machines', type_='foreignkey')
    op.create_foreign_key('virtual_machines_user_id_fkey', 'virtual_machines', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_virtual_machines_vmid'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_user_id'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_id'), table_name='virtual_machines')
    op.create_unique_constraint('virtual_machines_vmid_key', 'virtual_machines', ['vmid'])
    op.create_index('idx_vms_user_id', 'virtual_machines', ['user_id'], unique=False)
    op.create_index('idx_vms_status', 'virtual_machines', ['status'], unique=False)
    op.alter_column('virtual_machines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('virtual_machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('virtual_machines', 'storage',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('virtual_machines', 'proxmox_node',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('virtual_machines', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'creating'::character varying"))
    op.alter_column('virtual_machines', 'os_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ubuntu-24.04'::character varying"))
    op.alter_column('virtual_machines', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('users', 'max_cpu_cores')
    op.drop_column('users', 'max_vms')
    op.drop_column('users', 'max_ram_mb')
    op.drop_column('users', 'max_disk_gb')
    # ### end Alembic commands ###
