"""add excluded_storages to proxmox_servers

Revision ID: 7ed3d555f5b2
Revises: e4bc5fcdcd84
Create Date: 2026-01-28 03:23:09.085138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed3d555f5b2'
down_revision: Union[str, None] = 'e4bc5fcdcd84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxmox_servers', sa.Column('excluded_storages', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxmox_servers', 'excluded_storages')
    # ### end Alembic commands ###
