"""remove_vm_storage_iso_storage_from_proxmox_servers

Revision ID: e4bc5fcdcd84
Revises: 3cb6dfdd7cdb
Create Date: 2026-01-28 01:35:27.748424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4bc5fcdcd84'
down_revision: Union[str, None] = '3cb6dfdd7cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proxmox_servers', 'vm_storage')
    op.drop_column('proxmox_servers', 'iso_storage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proxmox_servers', sa.Column('iso_storage', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('proxmox_servers', sa.Column('vm_storage', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
